In [1]:
import tensorflow as tf

In [17]:
hello = tf.constant('hello world')
x = tf.constant([120, 100])

In [18]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [19]:
x.shape

TensorShape([2])

In [20]:
x

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([120, 100])>

In [21]:
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [28]:
y = tf.constant([[1, 2, 3], [4, 5, 6]])

In [29]:
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [58]:
power = x **2

In [33]:
y * 2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [34]:
x / 5

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([24., 20.])>

In [39]:
y @ tf.transpose(y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]])>

In [40]:
tf.transpose(y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [49]:
tf.concat([y, y, y], axis=0)

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])>

In [57]:
#tf.nn.softmax(x)

In [56]:
tf.convert_to_tensor([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [61]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS NOT** using the GPU
