In [1]:
import numpy as np

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
soflist = [[1,2,3], [4,5,6], [7,8,9]] 

In [5]:
np.array(soflist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.linspace(1,20, 7)

array([ 1.        ,  4.16666667,  7.33333333, 10.5       , 13.66666667,
       16.83333333, 20.        ])

In [9]:
np.random.rand(4)

array([0.77883662, 0.93248948, 0.5733587 , 0.70308123])

In [10]:
np.random.rand(4,3)

array([[0.06832455, 0.87893967, 0.37915715],
       [0.64373224, 0.43750232, 0.2500866 ],
       [0.8290073 , 0.09011158, 0.87522202],
       [0.69518232, 0.77191534, 0.88961196]])

In [11]:
np.random.randn(3)

array([-0.16511949, -0.77730042, -0.6053964 ])

In [12]:
np.random.randn(3,4)

array([[-1.71887328, -1.81879126, -2.28129465, -0.36903813],
       [ 0.82917238,  0.31137211, -1.3104747 ,  0.23893286],
       [-0.22670952, -1.32423274,  0.57396688,  0.13640442]])

In [13]:
np.random.randint(20,40)

34

In [14]:
np.random.randint(20,40,7)

array([29, 38, 34, 32, 23, 33, 27])

In [15]:
rar1 = np.arange(40)

In [16]:
rar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [17]:
rar1.reshape(5,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [18]:
rar2 = np.random.randint(1,100,20)

In [19]:
rar2

array([69, 31, 73,  2, 18, 15, 95, 71, 85, 42, 11, 84, 81, 36, 43, 26, 70,
       82, 35, 63])

In [20]:
rar2.reshape(4,5)

array([[69, 31, 73,  2, 18],
       [15, 95, 71, 85, 42],
       [11, 84, 81, 36, 43],
       [26, 70, 82, 35, 63]])

In [21]:
rar2.max()

95

In [22]:
rar1.min()

0

In [23]:
rar2.min()

2

In [24]:
rar1.argmax()

39

In [25]:
rar2.argmin()

3

In [26]:
rar2 = rar2.reshape(4,5)

In [27]:
rar2

array([[69, 31, 73,  2, 18],
       [15, 95, 71, 85, 42],
       [11, 84, 81, 36, 43],
       [26, 70, 82, 35, 63]])

In [28]:
rar2.shape

(4, 5)

In [29]:
rar2.dtype

dtype('int32')

In [30]:
rar1.dtype

dtype('int32')

In [31]:
arr1 = np.arange(1,11)

In [32]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr1[1]

2

In [34]:
arr1[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr1[1:4]

array([2, 3, 4])

In [36]:
arr1[1:9:2]

array([2, 4, 6, 8])

In [37]:
arr1[5:-1]

array([6, 7, 8, 9])

In [38]:
r_1 = np.arange(2,27,3)

In [39]:
r_2 = r_1.copy()

In [40]:
r_2 [2:5] = [7, 9, 11]

In [41]:
r_2

array([ 2,  5,  7,  9, 11, 17, 20, 23, 26])

In [42]:
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]] )

In [43]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
array_2d[2][2]

9

In [45]:
array_2d[2,2]

9

In [46]:
array_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [47]:
array_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [48]:
array_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [49]:
pl_arr = np.arange(10,21)

In [50]:
pl_arr [pl_arr<12]

array([10, 11])

In [51]:
pl_arr [pl_arr>12]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
pl_arr [pl_arr==12]

array([12])

In [53]:
trial_arr = np.arange(50).reshape(5,10)

In [54]:
trial_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
trial_arr[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [56]:
trial_arr[2:, 7:]

array([[27, 28, 29],
       [37, 38, 39],
       [47, 48, 49]])

In [57]:
trial_arr[2:,:3]

array([[20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]])

In [58]:
trial_arr[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [59]:
trial_arr[:3, 7:]

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29]])

In [60]:
arrl = np.arange(5,17)

In [61]:
arrl

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [62]:
arrl + arrl

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [63]:
arrl **2

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196, 225, 256],
      dtype=int32)

In [64]:
arrl **2 - arrl

array([ 20,  30,  42,  56,  72,  90, 110, 132, 156, 182, 210, 240])

In [65]:
arrl/np.arange(1,13)

array([5.        , 3.        , 2.33333333, 2.        , 1.8       ,
       1.66666667, 1.57142857, 1.5       , 1.44444444, 1.4       ,
       1.36363636, 1.33333333])

In [100]:
np.mean(np.random.randint(270,360))

0.9510639681125854