In [1]:
import numpy as np
import pandas as pd

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
soflist = [[1,2,3], [4,5,6], [7,8,9]] 

In [5]:
np.array(soflist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.linspace(1,20, 7)

array([ 1.        ,  4.16666667,  7.33333333, 10.5       , 13.66666667,
       16.83333333, 20.        ])

In [9]:
np.random.rand(4)

array([0.03673768, 0.12063546, 0.44455408, 0.97975799])

In [10]:
np.random.rand(4,3)

array([[0.45628926, 0.58600222, 0.09425817],
       [0.18932897, 0.11873988, 0.64054154],
       [0.17746889, 0.73599828, 0.06368477],
       [0.30610324, 0.33082728, 0.26009287]])

In [11]:
np.random.randn(3)

array([-1.79138406, -0.34912156,  1.68193828])

In [12]:
np.random.randn(3,4)

array([[-0.15330176, -0.63588978,  0.28526776,  2.2903598 ],
       [ 0.18829414,  0.0961606 , -0.03101964, -0.67312169],
       [ 1.50937628, -0.68174167,  0.57662559,  1.93325921]])

In [13]:
np.random.randint(20,40)

22

In [14]:
np.random.randint(20,40,7)

array([23, 28, 23, 21, 31, 25, 29])

In [15]:
rar1 = np.arange(40)

In [16]:
rar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [17]:
rar1.reshape(5,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [18]:
rar2 = np.random.randint(1,100,20)

In [19]:
rar2

array([22, 21, 72, 48, 18, 93,  1, 97,  6, 90, 62, 32, 54, 51, 15, 12, 54,
       17, 25,  5])

In [20]:
rar2.reshape(4,5)

array([[22, 21, 72, 48, 18],
       [93,  1, 97,  6, 90],
       [62, 32, 54, 51, 15],
       [12, 54, 17, 25,  5]])

In [21]:
rar2.max()

97

In [22]:
rar1.min()

0

In [23]:
rar2.min()

1

In [24]:
rar1.argmax()

39

In [25]:
rar2.argmin()

6

In [26]:
rar2 = rar2.reshape(4,5)

In [27]:
rar2

array([[22, 21, 72, 48, 18],
       [93,  1, 97,  6, 90],
       [62, 32, 54, 51, 15],
       [12, 54, 17, 25,  5]])

In [ ]:
rar2.shape

In [ ]:
rar2.dtype

In [ ]:
rar1.dtype

In [ ]:
pd.read_


How many people have the word Chief in their job title? (This is pretty tricky)

In [ ]:
def job_title(title):
    if 'chief' in title.lower().split():
        return True
    else:
        return False
    


In [ ]:
from plotly import __version__
pri

In [30]:
pl_arr = np.arange(10,21)

In [35]:
pl_arr[pl_arr>=15]

array([15, 16, 17, 18, 19, 20])